### ISSUE TITLE
更新1.0.5之后切换chat非常缓慢，点开设置也是一样都要好几秒才能切换过来

### ISSUE THREAD

**Issue by WifiStop** [MustangYM/OSXChatGpt#13]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/59257344/225855992-a492716e-d683-4df3-9e3b-ba7c9cf7b3ab.png">

**Comment by WifiStop** [comment]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/59257344/225856080-c05a11a8-7b8e-4c23-868a-a61ad06a4118.png">
设置甚至dian 点不开了

**Comment by CoderLineChan** [comment]
已经修复！已发1.0.6

**Comment by MustangYM** [comment]
试试[Beta 1.0.7](https://github.com/MustangYM/OSXChatGpt/releases)
