### ISSUE TITLE
功能建议&优化

### ISSUE THREAD

**Issue by LanYunDev** [MustangYM/OSXChatGpt#20]
1.能够记忆上次调整的窗口尺寸
2.输入框支持不再固定,能够跟随内容滚动.(一直固定在哪里,占了一大片空间浪费)
3.支持可选文本进行操作(比如复制,翻译等),而不是只能右键全选然后只有复制
4.参数支持自定义调节
5.部分界面进一步汉化,支持多主题选择.
6.有些东西可以参考[这个项目](https://github.com/GaiZhenbiao/ChuanhuChatGPT)
更多建议,日后再说,不过从初步来看,软件还是很不错的!

**Comment by CoderLineChan** [comment]
感谢您的宝贵意见！除了第二点，其他都已经实现了
