### ISSUE TITLE
考虑增加自定义的 prompt

### ISSUE THREAD

**Issue by flyingzl** [MustangYM/OSXChatGpt#22]
例如类似于如下效果：

<img width="513" alt="image" src="https://user-images.githubusercontent.com/492952/227822293-4b27589c-82a3-4e89-814b-b2005c5988e2.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/492952/227822350-24950121-5b74-4751-8ba5-bc2aea892d50.png">

**Comment by CoderLineChan** [comment]
v1.1.1已经新增
