### ISSUE TITLE
建议：增加accesstoken调用方式

### ISSUE THREAD

**Issue by raisons** [MustangYM/OSXChatGpt#23]
其实就是chat.openai.com的网页版，api赠送的只有3个月有效期。但是web版的免费，还可以使用plus。参考https://github.com/acheong08/ChatGPT 的v1

**Comment by CoderLineChan** [comment]
网页版本市面上有很多了，目前只做客户端，至于你说的api有效期问题，到时候再看吧，总会有办法的
