### ISSUE TITLE
回答框背景颜色和字体颜色相近，不太容易识别

### ISSUE THREAD

**Issue by Skylerliutian** [MustangYM/OSXChatGpt#28]
v1.1.1
<img width="650" alt="image" src="https://user-images.githubusercontent.com/49233429/228708644-6d81b155-e80c-4fee-b0b4-128a2c75218d.png">

**Comment by Skylerliutian** [comment]
补充：
自定义prompt也是上述情况
<img width="506" alt="image" src="https://user-images.githubusercontent.com/49233429/228710889-2bd43146-353c-49fe-9d32-606e846d980c.png">

**Comment by CoderLineChan** [comment]
1.1.2 已经适配了暗黑模式
