### ISSUE TITLE
能不能编译一个os x 11.7 的版本

### ISSUE THREAD

**Issue by starsea** [MustangYM/OSXChatGpt#29]
RT

**Comment by CoderLineChan** [comment]
非常抱歉了，这边使用的Markdown框架最低是12的，后面看情况有没有可能更换吧

**Comment by starsea** [comment]
> 非常抱歉了，这边使用的Markdown框架最低是12的，后面看情况有没有可能更换吧

swift-md-ui 没有低版本的吗 我尝试着rebuild 说是版本依赖比较高

**Comment by CoderLineChan** [comment]
这个牵扯到swiftUI的API了！低版本swiftUI少很多api的

**Comment by starsea** [comment]
这样的的吗 我没写过swift  我的本机swift  5.5.2-dev  xcode13.2.1

**Comment by CoderLineChan** [comment]
是的，你可以自己把Markdown换成Text，应该可以支持低版本的

**Comment by starsea** [comment]
Dependencies could not be resolved because 'swift-markdown-ui' >= 2.0.0 contains incompatible tools version (5.6.0) and root depends on 'swift-markdown-ui' 2.0.0..<3.0.0.

请教问题 为什么我在xcode toolchains 中指定了 swift 5.6.0 还是会报错

**Comment by CoderLineChan** [comment]
应该是你macOS版本的原因
