### ISSUE TITLE
Langs

### ISSUE THREAD

**Issue by SynthesOne** [MustangYM/OSXChatGpt#30]
请把所有的语言环放在一个单独的文件中，这样你就可以快速地把这个优秀的项目本地化为你自己的语言。谢谢你

**Comment by CoderLineChan** [comment]
非常感谢您的提议，虽然目前还没有做本地化，后面做的时候会考虑的，谢谢你

**Comment by CoderLineChan** [comment]
已经做了语言本地化，这个Issues关闭
