### ISSUE TITLE
新版1.1.6输入APIkey后还是不能用

### ISSUE THREAD

**Issue by lowkeygoto** [MustangYM/OSXChatGpt#38]
<img width="981" alt="QQ20230421-001447@2x" src="https://user-images.githubusercontent.com/77333398/233426131-2a5a81aa-c49c-48b3-a1f6-2c6fff7f390f.png">

**Comment by CoderLineChan** [comment]
请确保你的网络是否科学？

**Comment by CoderLineChan** [comment]
如无其他问题，这个issues即将关闭
