### ISSUE TITLE
参数设置

### ISSUE THREAD

**Issue by yld0818** [MustangYM/OSXChatGpt#43]
请问，模型无法改为GPT4是怎么回事
<img width="639" alt="截屏2023-05-17 10 17 02" src="https://github.com/MustangYM/OSXChatGpt/assets/79392044/86b4aa1c-0deb-4796-a565-c6098cd0bff9">

**Comment by CoderLineChan** [comment]
您好，报这个错，说明已经使用了gpt4去请求了，如果您没有gpt4的权限是无法请求成功的，如果您有权限，则稍后再次尝试应该是可以的

**Comment by CoderLineChan** [comment]
没有其他问题就关闭当前issue了
