### ISSUE TITLE
mac os 11都不能用，m1表示有被伤到了

### ISSUE THREAD

**Issue by qzmer1104** [MustangYM/OSXChatGpt#46]
大佬，兼容一下mac os 11，20年的m1的出厂系统，不想升级了
微信目前兼容到mac os 10，大佬行行好！

**Comment by CoderLineChan** [comment]
抱歉了~因为使用的是swiftUI，无法兼容低版本~抱歉了
https://github.com/MustangYM/OSXChatGpt/issues/29
