### ISSUE TITLE
不支持m1 吗

### ISSUE THREAD

**Issue by HansenCCC** [MustangYM/OSXChatGpt#5]
不支持m1 吗

**Comment by MustangYM** [comment]
支持

**Comment by HansenCCC** [comment]
您使用的是macOS 12.5.1。该应用程序要求macOS 13.0或更高版本。  系统版本要求太高了，能不能降低降低

**Comment by MustangYM** [comment]
会的, 请耐心等待一下.

**Comment by MustangYM** [comment]
> 您使用的是macOS 12.5.1。该应用程序要求macOS 13.0或更高版本。 系统版本要求太高了，能不能降低降低

已经支持macOS12
