### ISSUE TITLE
白色背景下，输入框的颜色显得比较突兀，不协调

### ISSUE THREAD

**Issue by tangb4c** [MustangYM/OSXChatGpt#7]
![image](https://user-images.githubusercontent.com/5152043/225193824-c24383f1-43c8-446d-b2ad-3cdc71c9e381.png)

**Comment by MustangYM** [comment]
你是什么版本的机器, 目前OSXChatGPT已经强制深色了. 晚点会发版本

**Comment by tangb4c** [comment]
> 你是什么版本的机器, 目前OSXChatGPT已经强制深色了. 晚点会发版本

iMac, 12.5.1 monterey, 系统主题选的是Light

**Comment by MustangYM** [comment]
试试[Beta 1.0.7](https://github.com/MustangYM/OSXChatGpt/releases)
