### ISSUE TITLE
markdown解析有问题，html代码会显示不全

### ISSUE THREAD

**Issue by Fooyao** [MustangYM/OSXChatGpt#8]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/6670270/225194971-fbef31cc-0480-4b26-a602-5e86b226ef4c.png">

**Comment by MustangYM** [comment]
帮忙贴一下完整的出bug的内容

**Comment by CoderLineChan** [comment]
估计是返回不全，试试新版本吧
